version: '3.8'
services:
  mariadb:
    container_name: 'docker-blog'
    image: mariadb:latest
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USERNAME=rifuki
    - MYSQL_PASSWORD=nande
    - MYSQL_DATABASE=db_ror
  
  phpmyadmin:
    image: phpmyadmin
    ports:
    - "8080:80"
    environment:
    - PMA_ARBITRARY=1